version: '3'

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true


  run:
    cmds:
      - go run main.go

  mysql:
    vars:
      HOST: 127.0.0.1
      USER: docker
      DB: sampledb
    cmds:
      - mysql -h {{.HOST}} -u {{.USER}} -D {{.DB}} -p

  migrate:
    cmds:
      - mysql -h 127.0.0.1 -u docker sampledb -p < createTable.sql
      - mysql -h 127.0.0.1 -u docker sampledb -p < insertData.sql

  sqlfluff:
    cmds:
      - find . -name '*.sql' | xargs sqlfluff lint --dialect=mysql

  sqlfluff_fix:
    cmds:
      - find . -name '*.sql' | xargs sqlfluff fix --dialect=mysql

  pod:
    vars:
      PROJECT: go_intermediate_book
    cmds:
      - cd Pod; podman-compose -p {{.PROJECT}} up --detach

  pod-rm:
    vars:
      POD: pod_go_intermediate_book
    cmds:
      - cd Pod; podman pod stop {{.POD}} && podman pod rm {{.POD}}

  test:
    cmds:
      - curl localhost:8080/hello
      - curl -s http://localhost:8080/article     -X POST -d '{"title":"a", "contents":"b", "user_name":"c"}'
      - curl localhost:8080/article/list
      - curl localhost:8080/article/1
      - curl localhost:8080/article/2
      - curl -s http://localhost:8080/article/nice -X POST -d '{"title":"a", "contents":"b", "user_name":"c"}'
      - curl -s http://localhost:8080/comment      -X POST -d '{"article_id":1, "message":"first comment"}'
