version: '3'

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true


  run:
    cmds:
      - go run main.go

  pod:
    cmds:
      - cd Pod; podman-compose -p go_intermediate_book up --detach

  pod-rm:
    cmds:
      - cd Pod; podman pod stop pod_go_intermediate_book && podman pod rm pod_go_intermediate_book

  test:
    cmds:
      - curl localhost:8080/hello
      - curl -s http://localhost:8080/article     -X POST -d '{"title":"a", "contents":"b", "user_name":"c"}'
      - curl localhost:8080/article/list
      - curl localhost:8080/article/1
      - curl localhost:8080/article/2
      - curl -s http://localhost:8080/article/nice -X POST -d '{"title":"a", "contents":"b", "user_name":"c"}'
      - curl -s http://localhost:8080/comment      -X POST -d '{"article_id":1, "message":"first comment"}'
